from .prompts import (
    COLLECTOR_SYSTEM, COLLECTOR_USER,
    ANALYST_A_SYSTEM, ANALYST_A_USER,
    ANALYST_B_SYSTEM, ANALYST_B_USER,
    QA_SYSTEM, QA_USER,
    WRITER_SYSTEM, WRITER_USER,
    THREAT_SCHEMA_NOTE,
)
